x-env: &env
    APP_ENV: prod
    APP_DEBUG: 1
    PROJECT_ROOT: /var/www/html
    MYSQL_ROOT_PASSWORD: app
    MYSQL_DATABASE: shopwell
    ADMINER_DEFAULT_SERVER: database
    SHOPWELL_HTTP_CACHE_ENABLED: 0
    DATABASE_URL: mysql://root:app@database:3306/shopwell
    APP_SECRET: 0000shopwellAAAA0000shopwellAAAA
    APP_URL: http://localhost:${PORT:-8011}
    SALES_CHANNEL_URL: http://localhost:${PORT:-8011}
    MAILER_DSN: smtp://mailpit:1025
    MAILPIT_BASE_URL: http://localhost:8013
    SERVICES_ENABLED: 1
    # TEST_WEB_INSTALLER: 1
    # SHOPWELL_SKIP_WEBINSTALLER: 0
    SHOPWELL_DISABLE_UPDATE_CHECK: "1"
    # SW_RECOVERY_NEXT_VERSION: 6.6.9999999.9999999
    # SW_RECOVERY_NEXT_BRANCH: dev-trunk
    # SW_RECOVERY_REPOSITORY: '{"type": "path", "url": "custom/packages/*", "options": { "symlink": true } }'
    INSTALL_LOCALE: en-US
    INSTALL_CURRENCY: USD
    PHP_OPCACHE_VALIDATE_TIMESTAMPS: 1

x-service: &service
    environment:
        <<: *env
    networks:
        - local

x-shopwell-volumes: &shopwell-volumes
    volumes:
        - jwt:/var/www/html/config/jwt
        - media:/var/www/html/public/media
        - theme:/var/www/html/public/theme
        - bundles:/var/www/html/public/bundles
        - thumbnail:/var/www/html/public/thumbnail
        - cache:/var/www/html/var/cache

services:
    database:
        <<: [*service]
        image: mysql:8.0
        entrypoint: ["sh", "-c", "docker-entrypoint.sh mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --sql-require-primary-key=ON"]
        tmpfs:
            - /var/lib/mysql:uid=999,gid=999
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            start_interval: 1s
            start_period: 10s

    adminer:
        <<: [*service]
        image: adminer:latest
        depends_on:
            database:
                condition: service_healthy
        ports:
            - "8012:8080"

    mailpit:
        <<: [*service]
        image: axllent/mailpit
        ports:
            - 8013:8025
        healthcheck:
            test: ["CMD", "wget", "-q", "--spider", "http://localhost:8025"]

    init-volumes:
        <<: [*shopwell-volumes]
        image: alpine:latest
        entrypoint: ["chown"]
        command: ["-R", "82:82", "/var/www/html"]
        user: root

    init:
        <<: [*service, *shopwell-volumes]
        image: ghcr.io/shopwell/acceptance-test-suite/test-image:${SHOPWELL_VERSION:-trunk}
        build:
            context: .
            dockerfile: test-image.Dockerfile
            args:
                - PHP_VERSION=${PHP_VERSION:-8.4}
                - SHOPWELL_VERSION=${SHOPWELL_VERSION:-trunk}
                - SHOPWELL_BUILD_SOURCE=${SHOPWELL_BUILD_SOURCE:-branch}
        depends_on:
            init-volumes:
                condition: service_completed_successfully
            database:
                condition: service_healthy
        entrypoint: ["vendor/bin/shopwell-deployment-helper"]
        command: ["run"]

    shopwell:
        extends:
            service: init
        depends_on:
            init:
                condition: service_completed_successfully
            mailpit:
                condition: service_healthy
        ports:
            - ${PORT:-8011}:8000
        entrypoint: ["/usr/bin/supervisord", "-c", "/etc/supervisord.conf"]
        command: []
        healthcheck:
            test: ["CMD", "curl", "-fsSL", "http://localhost:8000/api/_info/health-check"]

volumes:
    jwt:
    media:
    theme:
    bundles:
    thumbnail:
    cache:

networks:
    local:
